### ISSUE TITLE
v3.0.0 - Breaking changes/migration

### ISSUE THREAD

**Issue by renestalder** [arnoson/kirby-vite#10]
I saw that v3.0.0 dropped. The major version change would indicate breaking changes to me, but I can't exactly find anything about it.

Are there any breaking changes that were forgotten in the documentation?

**Comment by arnoson** [comment]
You're right I forgot to inlcude them in the documentation! I'll document them as soon as I find some time. Untill then a quick list:

- instead of the `.lock` file in the src folder a `.dev` file in the root folder is used to indicte development mode. Therefore the build/dev scripts can be simplified (see the [basic kit](https://github.com/arnoson/kirby-vite-basic-kit/) for an example).
- `arnoson.kirby-vite.dev` and `arnoson.kirby-vite.devServer` options are removed
- The `vite.config.js` file got much simpler because it uses [vite-plugin-kirby](https://github.com/arnoson/vite-plugin-kirby). No need to define vite's `server.port` and `server.origin` anymore (also see the basic kit for an example)
- `vite()->client()` is removed and as the client is inserted automatically
- legacy polyfills are inserted automatically (if `arnoson.kirby-vite.legacy` is enabled)

**Comment by arnoson** [comment]
I updated the [release](https://github.com/arnoson/kirby-vite/releases/tag/v3.0.0) information, did you manage to update to the new version or is there still something unclear/missing?

**Comment by renestalder** [comment]
@arnoson It's pending on my side, I didn't approach it without the necessary information. :)

Thank you very much, that's all what I needed.
