### ISSUE TITLE
How to access images?

### ISSUE THREAD

**Issue by dmnktoe** [arnoson/kirby-vite#22]
How to access images in `src/assets`? I'm experimenting with the snippets file and want to include an image. How can I access them, it always says 404 when I import them via `src="assets/images/logo.png`.

**Comment by arnoson** [comment]
Since you don't reference these specific assets from js/css vite can't know about them and so they are just normal kirby assets. So you can handle them just how you would handle assets without vite.
See https://github.com/arnoson/kirby-vite-multi-page-kit/issues/10 and https://github.com/arnoson/kirby-vite-basic-kit/issues/2

**Comment by dmnktoe** [comment]
Thanks for the answer - now it works. Such a good kit!
