### ISSUE TITLE
Error in production, but not in local

### ISSUE THREAD

**Issue by antoine3000** [arnoson/kirby-vite#44]
When I try to publish my site in production, I get this error:
`str_starts_with(): Argument #1 ($haystack) must be of type string, bool given`

from this file, line 51:
`/site/plugins/kirby-vite/packages/kirby-vite/Vite.php`
```
 if (str_starts_with($fullPath, $rootPath)) {
    return ltrim(substr($fullPath, strlen($rootPath)), DIRECTORY_SEPARATOR);
  }
```

Any idea what it could be?

**Comment by arnoson** [comment]
Can you share your setup with a minimal repository?
There used to be a similar issue but I forgot what caused it 🙈

**Comment by arnoson** [comment]
Ah I found it: maybe issue #40 can help you

**Comment by antoine3000** [comment]
Thanks for taking a look. I realised the website is looking for `/site/config/vite.config.php` but that file is in the `.gitignore`. And the error I posted above is caused when I stop ignoring that file and pushing it to the server. I also realised I can't use Node on my remote server, so no `npm install` available there. I guess that's the problem? If so, any idea how to bypass it?

**Comment by arnoson** [comment]
The file is git ignored by purpose, because it its auto-generated by the kirby-vite plugin. (I don't like to comit any files that are auto-generated or installed, like node_modules and composer's vendor) because you can recrate these files any time, so there is no need for them to end up in version control like git. But of course you have to upload the file.

I don't know how you deploy, but if you use git, you have to run `npm install`, `npm run build` and `composer install` on the server. If you can't use node then yes, you have to remove the auto-generated files from `.gitignore`. For simple website I also use a cheap shared hosting webspace without node and to deploy these website I use `rsync` or `lftp`. This way I still can ignore all auto-generated files from git, but I upload them to the server never the less. I also made a simple tool to help with `lftp`: [very-simple-deploy](https://github.com/very-simple/deploy), I you have ssh access you could also use [rploy](https://github.com/jongacnik/rploy). [Here](https://github.com/arnoson/kirby-kit) is an example setup of how I use my lftp tool with Kirby and Vite :)

**Comment by antoine3000** [comment]
amazing, many thanks for your reply!

**Comment by antoine3000** [comment]
fantastic, thanks a lot for your work!
